---
PORT: 3000
MONGODB:
  URL: 'mongodb://127.0.0.1:27017/test'
# for production
# LOGGERS:
#   base:
#     transport: null
# MONGODB_QUERY_OPTIONS:
  # maxTimeMs: 10000 # mongodb 查询超时时间
  # maxResultWindow: 10000 # 最大查询数的限制
